server:
  port: 8081

logging:
  level:
    root: INFO
    com.jsonschema: INFO

spring:
  thymeleaf:
    cache: false
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
      fail-fast: true
